<?php require __DIR__.'/bootstrap.php'; ?>
<!doctype html><html lang="pl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#fbf8f4"><title>Puchaty Zakątek — Umów wizytę</title><link rel="icon" href="../img/logo-transparent.png"><link rel="stylesheet" href="portal.css?v=2"></head><body>
<header class="site-header"><a href="./" class="brand" aria-label="Puchaty Zakątek — strona główna"><img src="../img/logo-transparent.png" alt=""><span>Puchaty Zakątek<small>PIELĘGNACJA Z MIŁOŚCIĄ</small></span></a><nav aria-label="Nawigacja"><a class="nav-calendar" href="#availability">Terminarz</a><a href="#visitsSection" id="myVisitsLink" hidden>Moje wizyty</a><button id="openLogin" class="button dark small">Zaloguj się ↗</button><button id="logout" class="button outline small" hidden>Wyloguj</button></nav></header>
<main>
<section class="hero"><div><p class="eyebrow"><span class="live-dot"></span> MAŁY SALON. WIELKA TROSKA.</p><h1><span class="desktop-headline">Dobry dzień zaczyna się<br>od <em>szczęśliwego psa.</em></span><span class="mobile-headline">Dobry dzień<br>dla <em>Twojego pupila.</em></span></h1><p class="hero-copy">Znajdź chwilę dla swojego pupila. Sprawdź wolne terminy<br class="desktop-break"> i zarezerwuj czas na spokojną pielęgnację.</p><a href="#availability" class="hero-link">Znajdź swój termin <span aria-hidden="true">↓</span></a></div><div class="hero-art" aria-hidden="true"><div class="logo-orbit"><img src="../img/logo-transparent.png" alt=""><span class="orbit-note">Z troską o każdy szczegół</span></div><span class="floating-note"><i>♡</i> Tu liczy się Twój pupil</span></div></section>
<div class="service-strip"><span><b>01</b> Sprawdź dostępność</span><span><b>02</b> Zaloguj się i wybierz psa</span><span><b>03</b> Potwierdź wizytę</span><span class="duration-pill">◷ &nbsp; 3 godziny tylko dla Twojego psa</span></div>
<p id="message" role="status" aria-live="polite"><?php echo htmlspecialchars((string)($_SESSION['pz_notice']??''),ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8'); unset($_SESSION['pz_notice']); ?></p>
<section id="availability" class="calendar-panel" aria-labelledby="calendarTitle"><div class="calendar-heading"><div><p class="eyebrow">TWÓJ PUPIL MA U NAS SWÓJ CZAS</p><h2 id="calendarTitle">Zaplanuj następną wizytę<span class="title-dot">.</span></h2></div><div class="availability-summary"><span class="live-dot"></span><span id="availabilityCount">Sprawdzamy dostępność…</span></div></div>
<div class="calendar-toolbar"><div class="range-navigation"><button id="previous" class="icon-button" aria-label="Poprzednie 7 dni">←</button><h3 id="rangeTitle">Terminarz</h3><button id="next" class="icon-button" aria-label="Następne 7 dni">→</button><button id="today" class="button outline small">Dzisiaj</button></div><div class="calendar-tools"><label class="date-picker"><span>Przejdź do dnia</span><input id="from" type="date" aria-label="Pierwszy dzień terminarza"></label><button id="refresh" class="icon-button" aria-label="Odśwież dostępność">↻</button></div></div>
<div class="legend"><span><i class="free-dot"></i>Wolny termin</span><span><i class="busy-dot"></i>Zajęty</span><span><i class="closed-dot"></i>Niedostępny</span><small>Czas polski · Rezerwacje minimum godzinę do przodu</small></div>
<div id="mobileDays" class="mobile-days" aria-label="Wybierz dzień"></div><div id="calendar" class="calendar" aria-live="polite"><p class="loading">Za chwilę pokażemy wolne terminy…</p></div>
<div class="calendar-footer"><p><span aria-hidden="true">♡</span> Przyjmujemy maksymalnie 3 psy dziennie, aby każdemu poświęcić pełną uwagę.</p><span>Wybierz miętowy kafelek, aby umówić wizytę ↗</span></div></section>
<section id="guestNote" class="guest-note"><div class="note-symbol" aria-hidden="true">↗</div><div><h3>Najpierw znajdź termin. Potem się zaloguj.</h3><p>Kalendarz jest dostępny dla każdego. Twoje dane i szczegóły wizyty zobaczysz wyłącznie na swoim koncie.</p></div><button id="guestLogin" class="button outline">Przejdź do konta</button></section>
<div id="customer" hidden><section class="account-heading"><div><p class="eyebrow">TWOJA STREFA</p><h2 id="who"></h2></div><form id="linkGoogle" method="post" action="google.php" hidden><input type="hidden" name="csrf"><button class="button outline small">Połącz Google</button></form></section>
<div class="account-grid"><div><section id="profileCard" class="card" hidden><h3>Poznajmy się</h3><p>Uzupełnij dane, żeby zarezerwować pierwszą wizytę.</p><form id="profile"><label>Imię i nazwisko<input name="name" maxlength="128" autocomplete="name" required></label><label>Telefon<input name="phone" maxlength="20" type="tel" autocomplete="tel" required></label><button class="button dark">Zapisz moje dane</button></form><p class="muted">Masz już kartotekę w salonie? Poproś obsługę o połączenie jej z kontem przed dodaniem psa.</p></section>
<section class="card"><div class="section-title"><h3>Twoi pupile</h3><button id="showDog" class="button outline small">+ Dodaj psa</button></div><label>Pies na wizytę<select id="dogs"><option value="">Najpierw uzupełnij dane</option></select></label><form id="dog" hidden><label>Imię psa<input name="name" maxlength="128" required></label><label>Rasa (opcjonalnie)<input name="breed" maxlength="128"></label><button class="button dark">Zapisz psa</button></form></section></div>
<section id="booking" class="card booking-card" hidden><p class="eyebrow">JUŻ PRAWIE GOTOWE</p><h3>Twój wybrany termin</h3><p id="bookingText"></p><p class="muted">Termin zostanie zarezerwowany po potwierdzeniu. Jego dostępność sprawdzimy ponownie przy zapisie.</p><button id="confirmBooking" class="button dark">Potwierdzam rezerwację ↗</button><button id="cancelBooking" class="button text-button">Zmień termin</button></section>
<section id="visitsSection" class="card visits-card"><div class="section-title"><h3>Moje wizyty</h3><span class="eyebrow">DO ZOBACZENIA!</span></div><div id="visits"></div></section></div></div>
</main><footer class="site-footer"><a href="./" class="footer-brand">Puchaty Zakątek<span>Pielęgnacja, która zaczyna się od troski.</span></a><a id="privacyFooter" href="privacy.html">Polityka prywatności</a><a href="../index.php">Panel salonu ↗</a><span>Do zobaczenia w salonie ♡</span></footer>
<dialog id="loginModal" aria-labelledby="loginTitle"><button id="closeLogin" class="modal-close icon-button" aria-label="Zamknij logowanie">×</button><section id="login"><img class="login-logo" src="../img/logo-transparent.png" alt="Logo Puchaty Zakątek"><p class="eyebrow">WITAJ W PUCHATYM ZAKĄTKU</p><h2 id="loginTitle">Jeszcze chwila<br>i widzimy się w salonie.</h2><p id="loginSelection" class="selection-note" hidden></p><p class="muted">Zaloguj się lub załóż konto, aby zarezerwować wizytę.</p><form id="google" method="post" action="google.php" hidden><input type="hidden" name="csrf"><button class="button outline full">Kontynuuj z Google ↗</button></form><div id="emailDivider" class="divider">lub przez e-mail</div><form id="email" hidden><label>Twój adres e-mail<input name="email" type="email" maxlength="128" autocomplete="email" placeholder="ty@przyklad.pl" required></label><button class="button dark full">Wyślij kod / załóż konto</button><p class="muted">Bez hasła. Wyślemy jednorazowy kod ważny 10 minut.</p></form><form id="verify" hidden><label>Kod z wiadomości<input name="code" inputmode="numeric" pattern="[0-9]{8}" maxlength="8" autocomplete="one-time-code" required></label><button class="button dark full">Potwierdź i wejdź</button></form><p id="loginMessage" role="status" aria-live="polite"></p><p class="privacy-note">Twoje dane służą do obsługi konta i wizyt. <a id="privacy" href="privacy.html" target="_blank" rel="noopener noreferrer">Informacja o prywatności</a>.</p></section></dialog>
<script src="portal.js?v=2" defer></script></body></html>
