'use strict';
let commerce=null,ndgSummary=null;
async function refreshCommerce(){commerce=await api('commerce');renderCommerce();}
function actionBtn(text,action,id='',cls='ghost'){return `<button type="button" class="btn ${cls}" data-commerce="${action}" data-id="${esc(id)}">${esc(text)}</button>`;}
function renderCommerce(){
 if(!commerce)return;
 $('documentsPanel').innerHTML='<h3>Dokumenty sprzedaży</h3><p>Nowe dokumenty: faktury dla konsumentów, sprzedaż zwolniona z VAT (art. 113). Starsze dokumenty pozostają w historii. Dokument z wizyty nie zwiększa ponownie przychodu.</p>'+(canWrite()?actionBtn('+ Nowy dokument','newdoc','','primary'):'')+table(['Numer','Daty','Nabywca','Wartość','Termin','Stan','Akcje'],commerce.documents.map(d=>row([esc(d.number),esc(d.issueDate)+'<br>'+esc(d.saleDate),esc(d.buyer?.nom||data.clients.find(c=>Number(c.id)===Number(d.clientId))?.name||'Klient #'+d.clientId),money(d.total),esc(d.dueDate)+(d.received?'<br>Opłacono':''),esc({draft:'Szkic',issued:'Wystawiony',void:'Anulowany'}[d.state]),actionBtn('Podgląd','preview',d.id)+(d.visitId?actionBtn('Potwierdzenie 80 mm','printvisit',d.visitId):'')+(canWrite()&&d.state==='draft'?actionBtn('Edytuj','editdoc',d.id)+actionBtn('Wystaw','issue',d.id):'')+(canWrite()&&d.state==='issued'&&!d.received?actionBtn('Potwierdź wpłatę','docpaid',d.id):'')+(canWrite()&&!d.visitId&&d.state!=='void'&&!d.received?actionBtn('Anuluj','void',d.id,'danger'):'')])));
 $('documentsPanel').innerHTML+='<details><summary>Dokument z rozliczonej wizyty</summary>'+table(['Wizyta','Klient / pies',''],data.visits.filter(v=>v.status==='completed').map(v=>row([esc(v.visit_date),esc(v.client)+' / '+esc(v.dog),actionBtn(commerce.documents.some(d=>Number(d.visitId)===Number(v.rowid))?'Otwórz dokument':'Utwórz dokument','visitpreview',v.rowid)])))+'</details>';
 $('catalogPanel').innerHTML='<h3>Towary i usługi</h3>'+(boot.manage?actionBtn('+ Dodaj pozycję','newproduct','','primary')+actionBtn('Jednostki miary','units'):'')+table(['Nazwa','Rodzaj','JM','EAN','Stan','Cena',''],commerce.catalog.map(s=>row([esc(s.name)+(s.active===false?' (archiwum)':''),s.kind==='product'?'Towar':'Usługa',esc(commerce.units.find(u=>u.id===(s.unit||'usl'))?.short),esc(s.ean),s.kind==='product'?(s.stock||0)/1000:'—',money(s.price),boot.manage?actionBtn('Edytuj','product',s.id):''])));
 $('businessPanel').innerHTML='<h3>NDG i raporty</h3><p>Limit ustawowy na 2026 r.: 10 813,50 zł przychodu należnego na kwartał. Własne progi miesięczne są dodatkowymi ustawieniami.</p>'+(boot.manage?actionBtn('Dane sprzedawcy','seller')+actionBtn('Własne limity','limits')+actionBtn('Realizacja progów','limitreport')+actionBtn('Ewidencja NDG','ndg'):'')+actionBtn('Raport sprzedaży i kosztów','reports')+actionBtn('Pomoc','help')+(boot.admin?actionBtn('Kopie bezpieczeństwa','backup'):'')+'<div id="commerceReport"></div>';
 document.querySelectorAll('[data-edit-client]').forEach(b=>{if(!b.parentElement.querySelector('[data-commerce="clientreport"]'))b.insertAdjacentHTML('afterend',actionBtn('Obrót / raport','clientreport',b.dataset.editClient));});
 const rows=$('expenseList')?.querySelectorAll('tbody tr');if(rows)rows.forEach((r,i)=>{const e=data.expenses[i];if(e&&canWrite()&&!r.querySelector('[data-commerce="expense"]'))r.lastElementChild.insertAdjacentHTML('beforeend',actionBtn('Edytuj','expense',e.rowid)+actionBtn('Usuń','removeexpense',e.rowid,'danger'));});
}
function productForm(id){
 const s=commerce.catalog.find(s=>s.id===id)||{id:crypto.randomUUID(),kind:'service',unit:'usl',stock:0,price:0,active:true};
 modal(id?'Edytuj pozycję':'Nowa pozycja',field('name','Nazwa',s.name,'text','required')+selectField('kind','Rodzaj',[['service','Usługa'],['product','Towar']],s.kind||'service')+selectField('unit','Jednostka',commerce.units.map(u=>[u.id,u.short+' — '+u.name]),s.unit||'usl')+field('ean','EAN',s.ean)+field('price','Cena brutto (zł)',s.price/100,'number','min="0.01" step="0.01" required')+field('stock','Stan towaru',(s.stock||0)/1000,'number','min="0" step="0.001" required')+field('reason','Powód zmiany stanu / stan początkowy')+selectField('active','Widoczność',[['1','Aktywna'],['0','Archiwum']],s.active===false?'0':'1')+selectField('addon','Dodatek',[['0','Nie'],['1','Tak']],s.addon?'1':'0'),async v=>{await api('catalog',{...v,id:s.id,kind:id?(s.kind||'service'):v.kind,active:v.active==='1',addon:v.addon==='1'});await refresh();message('Katalog zapisany.');});
 if(id)$('f_kind').disabled=true;
}
function unitForm(){modal('Jednostki miary',table(['Kod','Skrót','Nazwa',''],commerce.units.map(u=>row([esc(u.id),esc(u.short),esc(u.name),actionBtn('Edytuj','editunit',u.id)+actionBtn('Usuń','removeunit',u.id,'danger')])))+field('id','Nowy kod','','text','required pattern="[a-zA-Z0-9_-]+"')+field('short','Skrót','','text','required')+field('name','Pełna nazwa','','text','required'),async v=>{await api('unit',v);await refresh();message('Jednostka dodana.');});}
function documentLine(line={}){
 const s=commerce.catalog.find(s=>s.id===line.productId)||commerce.catalog.find(s=>s.active!==false);if(!s)return '';
 return `<tr class="document-line"><td><select class="select" data-line-product>${commerce.catalog.filter(p=>p.active!==false||p.id===line.productId).map(p=>`<option value="${esc(p.id)}" ${p.id===s.id?'selected':''}>${esc(p.name)}${p.active===false?' (archiwum — zmień pozycję)':''}</option>`).join('')}</select></td><td><input aria-label="Ilość" class="input" data-line-qty type="number" min="0.001" step="0.001" value="${line.qty?line.qty/1000:1}" required></td><td><input aria-label="Cena brutto" class="input" data-line-price type="number" min="0" step="0.01" value="${(line.price??s.price)/100}" required></td><td><select aria-label="VAT" class="select" data-line-vat>${['zw'].map(v=>`<option ${v===(line.vat||'zw')?'selected':''}>${v}</option>`).join('')}</select></td><td>${actionBtn('Usuń','removeline')}</td></tr>`;
}
function documentForm(id){
 if(!data.clients.length||!commerce.catalog.some(s=>s.active!==false)){message('Dodaj klienta oraz pozycję katalogu.',true);return;}
 const d=commerce.documents.find(d=>d.id===id)||{id:crypto.randomUUID(),version:0,issueDate:today(),saleDate:today(),dueDate:today(),payment:'Gotówka',type:'faktura',lines:[]};
 modal(id?'Edytuj szkic':'Nowy dokument',selectField('clientId','Nabywca',data.clients.map(c=>[c.id,c.name]),d.clientId)+selectField('type','Rodzaj',[['faktura','Faktura — sprzedaż zwolniona z VAT']],d.type)+field('issueDate','Data wystawienia',d.issueDate,'date','required')+field('saleDate','Data sprzedaży',d.saleDate,'date','required')+selectField('payment','Forma płatności',['Gotówka','Karta','BLIK','Przelew'].map(x=>[x,x]),d.payment)+field('defer','Dni odroczenia',Math.round((new Date(d.dueDate)-new Date(d.issueDate))/86400000),'number','min="0" max="3650"')+field('dueDate','Termin płatności',d.dueDate,'date','required')+'<div style="grid-column:1/-1;overflow:auto"><table><thead><tr><th>Pozycja</th><th>Ilość</th><th>Cena brutto</th><th>VAT</th><th></th></tr></thead><tbody id="documentLines">'+(d.lines.length?d.lines.map(documentLine).join(''):documentLine())+'</tbody></table>'+actionBtn('+ Dodaj pozycję','addline')+'<details><summary>Wybierz kilka pozycji</summary>'+commerce.catalog.filter(s=>s.active!==false).map(s=>'<label style="display:block"><input type="checkbox" data-batch-product="'+esc(s.id)+'"> '+esc(s.name)+'</label>').join('')+actionBtn('Dodaj zaznaczone','batchlines')+'</details>'+'<p id="documentSum"></p></div>'+noteField('notes','Uwagi',d.notes),async values=>{
  const items=[...$('documentLines').querySelectorAll('tr')].map(r=>({productId:r.querySelector('[data-line-product]').value,quantity:r.querySelector('[data-line-qty]').value,price:r.querySelector('[data-line-price]').value,vat:r.querySelector('[data-line-vat]').value}));
  await api('document',{...values,id:d.id,version:d.version,items});await refresh();message('Szkic zapisany. Wybierz Wystaw, aby nadać numer.');
 });documentDates('payment');documentSum();
}
function documentDates(changed){
 if(!$('documentLines'))return;const cash=['Gotówka','Karta'].includes($('f_payment').value);$('f_dueDate').readOnly=cash;$('f_defer').readOnly=cash;
 if(cash){$('f_dueDate').value=$('f_issueDate').value;$('f_defer').value='0';return;}
 if(changed==='defer'||changed==='issueDate'){const d=new Date($('f_issueDate').value+'T12:00:00');d.setDate(d.getDate()+Number($('f_defer').value||0));if(!isNaN(d))$('f_dueDate').value=calendarIso(d);}
 if(changed==='dueDate')$('f_defer').value=String(Math.round((new Date($('f_dueDate').value)-new Date($('f_issueDate').value))/86400000));
}
function documentSum(){if(!$('documentLines'))return;const sum=[...$('documentLines').querySelectorAll('tr')].reduce((n,r)=>n+Math.round(Number(r.querySelector('[data-line-qty]').value)*Number(r.querySelector('[data-line-price]').value)*100),0);$('documentSum').textContent='Razem: '+money(sum)+' — '+amountWords(sum);}
function amountWords(cents){
 const one=['zero','jeden','dwa','trzy','cztery','pięć','sześć','siedem','osiem','dziewięć'],teen=['dziesięć','jedenaście','dwanaście','trzynaście','czternaście','piętnaście','szesnaście','siedemnaście','osiemnaście','dziewiętnaście'],ten=['','','dwadzieścia','trzydzieści','czterdzieści','pięćdziesiąt','sześćdziesiąt','siedemdziesiąt','osiemdziesiąt','dziewięćdziesiąt'],hundred=['','sto','dwieście','trzysta','czterysta','pięćset','sześćset','siedemset','osiemset','dziewięćset'];
 const triple=n=>{let w=[];if(n>=100)w.push(hundred[Math.floor(n/100)]);n%=100;if(n>=10&&n<20)w.push(teen[n-10]);else{if(n>=20)w.push(ten[Math.floor(n/10)]);if(n%10)w.push(one[n%10]);}return w.join(' ');};
 const ending=(n,forms)=>n===1?forms[0]:(n%10>=2&&n%10<=4&&!(n%100>=12&&n%100<=14)?forms[1]:forms[2]);
 let n=Math.floor(cents/100),parts=[];for(const [size,forms] of [[1000000,['milion','miliony','milionów']],[1000,['tysiąc','tysiące','tysięcy']]]){const q=Math.floor(n/size);if(q){parts.push((q===1&&size===1000?'':triple(q)+' ')+ending(q,forms));n%=size;}}if(n||!parts.length)parts.push(n?triple(n):'zero');return parts.join(' ')+' '+ending(Math.floor(cents/100),['złoty','złote','złotych'])+' '+String(cents%100).padStart(2,'0')+'/100';
}
function documentPreview(id){const d=commerce.documents.find(d=>d.id===id);if(!d)return;modal(d.number,'<div style="grid-column:1/-1"><h3>'+esc({rachunek:'Rachunek',faktura:'Faktura',potwierdzenie:'Potwierdzenie niefiskalne'}[d.type])+'</h3><p>'+esc(d.buyer?.nom||data.clients.find(c=>Number(c.id)===Number(d.clientId))?.name)+'</p>'+table(['Pozycja','Ilość','JM','Cena brutto','VAT','Wartość'],d.lines.map(l=>row([esc(l.name),l.qty/1000,esc(l.unit),money(l.price),esc(l.vat),money(l.total)])))+'<p>Razem: <strong>'+money(d.total)+'</strong><br>'+esc(amountWords(d.total))+'</p><p>Termin: '+esc(d.dueDate)+' • '+esc(d.payment)+'</p><p>'+esc(d.notes)+'</p><a class="btn primary" target="_blank" rel="noopener" href="document.php?id='+encodeURIComponent(d.id)+'">Otwórz PDF / drukuj</a></div>',null);}
function sellerForm(){const s=commerce.seller||{};modal('Dane sprzedawcy','<p style="grid-column:1/-1">Wpisz imię i nazwisko sprzedawcy oraz pełny adres — sama nazwa salonu nie wystarczy. Profil dotyczy sprzedaży konsumentom poza KSeF. Działalność nierejestrowana sama w sobie nie oznacza zwolnienia z VAT.</p>'+selectField('taxProfile','Profil podatkowy',[['','Wybierz po sprawdzeniu swojego statusu'],['ndg_consumer_art113','Korzystam ze zwolnienia z VAT (art. 113), sprzedaż konsumentom']],s.taxProfile||'')+field('name','Imię i nazwisko sprzedawcy (możesz dopisać nazwę salonu)',s.name||'','text','required')+field('address','Pełny adres',s.address||data.config.address,'text','required')+field('nip','NIP — opcjonalny; nie wpisuj PESEL',s.nip)+field('bank','Bank',s.bank)+field('account','Numer rachunku',s.account)+field('exemption','Podstawa zwolnienia — opcjonalny opis (art. 113)',s.exemption)+'<label>Logo na nowych dokumentach (JPG, do 256 KB)<input id="sellerLogo" type="file" accept="image/jpeg"></label>'+selectField('resetLogo','Logo domyślne',[[0,'Zachowaj obecne'],[1,'Przywróć logo Puchatego Zakątka']],0),async v=>{const file=$('sellerLogo').files[0];if(file){if(file.size>262144)throw new Error('Logo może mieć do 256 KB.');v.logo=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(new Error('Nie odczytano logo.'));r.readAsDataURL(file);});}else if(v.resetLogo==='1')v.logo=null;await api('businesssettings',v);await refresh();message('Dane sprzedawcy zapisane.');});}
function limitsForm(){const year=new Date().getFullYear(),limits=commerce.limits[year]||Array(12).fill(0);modal('Własne progi przychodu', '<p>To dodatkowe progi użytkownika. Nie zastępują ustawowego limitu kwartalnego NDG.</p>'+field('year','Rok',year,'number','required min="2020" max="2100"')+limits.map((x,i)=>field('month_'+i,'Miesiąc '+(i+1),x/100,'number','required min="0" step="0.01"')).join(''),async v=>{await api('limits',{year:v.year,months:Array.from({length:12},(_,i)=>v['month_'+i])});await refresh();message('Limity zapisane.');});}
function editExpenseForm(id){const e=data.expenses.find(e=>Number(e.rowid)===Number(id));if(!e)return;modal('Edytuj koszt',field('date','Data',e.expense_date,'date','required')+field('document','Numer dokumentu',e.document_no,'text','required')+selectField('clientId','Kontrahent z kartoteki',[[0,'Wpisany ręcznie'],...data.clients.map(c=>[c.id,c.name])],e.meta?.clientId||0)+field('supplier','Nazwa dostawcy',e.supplier,'text','required')+field('category','Kategoria',e.category,'text','required')+field('amount','Kwota brutto',e.amount_gross,'number','required min="0.01" step="0.01"')+noteField('description','Opis',e.description)+noteField('note','Opis własny',e.meta?.note),async v=>{await api('editexpense',{...v,id});await refresh();message('Koszt zapisany.');});}
function backupForm(){modal('Kopie bezpieczeństwa', '<p>Kopia obejmuje całą bazę MariaDB Dolibarra. Ze względu na dostęp do innych modułów operację wykonuje administrator.</p><p>Pobierz skrypt i uruchom go w PowerShellu na komputerze z Dockerem. Kopie SQL trafią do Dokumenty / Puchaty-kopie. Przywracanie wymaga wskazania pliku i wpisania potwierdzenia; przed nim powstaje dodatkowa kopia aktualnej bazy.</p>'+actionBtn('Pobierz skrypt kopii','downloadbackup')+actionBtn('Pobierz skrypt przywracania','downloadrestore'),null);}
function exportCommerceCSV(name,rows){const value=v=>{let s=String(v??'');if(/^[=+@\-\t\r]/.test(s))s="'"+s;return '"'+s.replaceAll('"','""')+'"';};const blob=new Blob(['\ufeff'+rows.map(r=>r.map(value).join(';')).join('\r\n')],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
function reportForm(clientId=0){const year=new Date().getFullYear();modal(clientId?'Sprzedaż klienta':'Raport sprzedaży i kosztów',field('from','Od',year+'-01-01','date','required')+field('to','Do',year+'-12-31','date','required'),async v=>{if(v.from>v.to)throw new Error('Nieprawidłowy zakres dat.');showView('business');reportCommerce(v.from,v.to,Number(clientId));});}
function reportCommerce(from,to,clientId){
 const inRange=d=>d>=from&&d<=to;const sales=data.visits.filter(v=>v.status==='completed'&&inRange((v.paymentState.completedDate||v.visit_date).slice(0,10))&&(!clientId||Number(v.fk_soc)===clientId)).map(v=>({date:(v.paymentState.completedDate||v.visit_date).slice(0,10),number:'Wizyta #'+v.rowid,client:v.client,total:Math.round(Number(v.amount_total)*100),payment:v.payment_type||'Nie określono'}));
 commerce.documents.filter(d=>d.number!=='Szkic'&&!d.visitId&&(!clientId||Number(d.clientId)===clientId)).forEach(d=>{if(inRange(d.saleDate))sales.push({date:d.saleDate,number:d.number,client:d.buyer.nom,payment:d.payment||'Nie określono',total:d.total});if(d.state==='void'&&inRange(d.voidDate))sales.push({date:d.voidDate,number:'Anulowanie '+d.number,client:d.buyer.nom,payment:d.payment||'Nie określono',total:-d.total});});sales.sort((a,b)=>a.date.localeCompare(b.date));
 const costs=clientId?[]:data.expenses.filter(e=>inRange(e.expense_date));const total=sales.reduce((n,s)=>n+s.total,0),expense=costs.reduce((n,e)=>n+Math.round(Number(e.amount_gross)*100),0);
 $('commerceReport').innerHTML='<h3>'+esc(clientId?'Sprzedaż klienta':'Sprzedaż i koszty')+' '+esc(from)+' — '+esc(to)+'</h3>'+pzSalesDashboard(from,to,sales,costs,clientId)+'<p>Sprzedaż: <strong>'+money(total)+'</strong>'+(clientId?'':' • Koszty: '+money(expense))+'</p>'+table(['Data','Dokument','Klient','Kwota'],sales.map(s=>row([esc(s.date),esc(s.number),esc(s.client),money(s.total)])))+(clientId?'':table(['Data','Dokument kosztu','Dostawca','Kwota'],costs.map(e=>row([esc(e.expense_date),esc(e.document_no),esc(e.supplier),money(Math.round(Number(e.amount_gross)*100))]))))+actionBtn('Eksport CSV','exportcurrent')+actionBtn('Drukuj / zapisz PDF','printreport');
 window.pzReportRows=[['Rodzaj','Data','Dokument','Kontrahent','Kwota PLN'],...sales.map(s=>['Sprzedaż',s.date,s.number,s.client,(s.total/100).toFixed(2)]),...costs.map(e=>['Koszt',e.expense_date,e.document_no,e.supplier,e.amount_gross])];
}
document.addEventListener('input',e=>{if(e.target.closest('#documentLines'))documentSum();if(['f_defer','f_issueDate','f_dueDate'].includes(e.target.id))documentDates(e.target.id.slice(2));});
document.addEventListener('change',e=>{if(e.target.matches('[data-line-product]')){const s=commerce.catalog.find(s=>s.id===e.target.value);e.target.closest('tr').querySelector('[data-line-price]').value=s.price/100;documentSum();}if(e.target.id==='f_clientId'&&$('f_supplier'))$('f_supplier').value=data.clients.find(c=>Number(c.id)===Number(e.target.value))?.name||'';if(e.target.id==='f_year'&&$('f_month_0')){const m=commerce.limits[e.target.value]||Array(12).fill(0);m.forEach((v,i)=>$('f_month_'+i).value=v/100);}if(e.target.id?.startsWith('f_'))documentDates(e.target.id.slice(2));});
document.addEventListener('click',async e=>{
 const b=e.target.closest('[data-commerce]');if(!b)return;e.preventDefault();const id=b.dataset.id,action=b.dataset.commerce;
 try{
  if(action==='newproduct'||action==='product')productForm(id);
  if(action==='units')unitForm();
  if(action==='editunit'){const u=commerce.units.find(u=>u.id===id);modal('Edytuj jednostkę',field('short','Skrót',u.short,'text','required')+field('name','Nazwa',u.name,'text','required'),async v=>{await api('unit',{...v,id});await refresh();});}
  if(action==='removeunit'){await api('unit',{id,delete:true});$('pzModal').close();await refresh();}
  if(action==='newdoc'||action==='editdoc')documentForm(id);
  if(action==='addline'){$('documentLines').insertAdjacentHTML('beforeend',documentLine());documentSum();}
  if(action==='batchlines'){document.querySelectorAll('[data-batch-product]:checked').forEach(c=>{$('documentLines').insertAdjacentHTML('beforeend',documentLine({productId:c.dataset.batchProduct}));c.checked=false;});documentSum();}
  if(action==='removeline'){b.closest('tr').remove();documentSum();}
  if(action==='preview')documentPreview(id);
  if(action==='issue'){const d=commerce.documents.find(d=>d.id===id);modal('Wystawić dokument?', '<p>Dokument otrzyma kolejny numer i zostanie zamknięty do edycji. Stan towarów zostanie pomniejszony.</p>',async()=>{await api('issuedocument',{id,version:d.version});await refresh();message('Dokument wystawiony.');});}
  if(action==='printvisit')await printReceipt(Number(id));
  if(action==='visitpreview'){const visitId=Number(id)||lastReceipt,d=commerce.documents.find(d=>Number(d.visitId)===visitId);if(d)documentPreview(d.id);else if(canWrite()){const r=await api('visitdocument',{id:visitId});await refresh();documentPreview(r.id);}else message('Starsza wizyta nie ma dokumentu. Poproś osobę z uprawnieniami do zapisu.',true);}
  if(action==='visitdoc'){const r=await api('visitdocument',{id});await refresh();documentPreview(r.id);}
  if(action==='docpaid')modal('Potwierdź otrzymanie całej kwoty',field('date','Data otrzymania wpłaty',today(),'date','required'),async v=>{await api('paiddocument',{...v,id});await refresh();message('Wpłata zapisana.');});
  if(action==='void')modal('Anuluj dokument',noteField('reason','Powód anulowania'),async v=>{await api('voiddocument',{...v,id});await refresh();message('Dokument anulowany.');});
  if(action==='limitreport'){modal('Realizacja progów',field('year','Rok',new Date().getFullYear(),'number','min="2020" max="2100" required'),async v=>{const n=await api('ndg',undefined,{year:v.year}),limits=commerce.limits[v.year]||Array(12).fill(0),due=Array(12).fill(0);n.entries.filter(e=>e.kind==='due').forEach(e=>due[Number(e.date.slice(5,7))-1]+=e.amount);showView('business');$('commerceReport').innerHTML='<h3>Własne progi — '+esc(v.year)+'</h3><p>Roczna suma progów: '+money(limits.reduce((a,b)=>a+b,0))+' • Przychód należny: '+money(due.reduce((a,b)=>a+b,0))+'</p>'+pzLimitDashboard(limits.map((_,i)=>String(i+1).padStart(2,'0')+'.'+v.year),due,limits,'Własne progi miesięczne')+table(['Miesiąc','Przychód należny','Własny próg','Pozostało'],limits.map((x,i)=>row([i+1,money(due[i]),x?money(x):'Nie ustawiono',x?(due[i]>x?'<strong style="color:#a32644">Przekroczono o '+money(due[i]-x)+'</strong>':money(x-due[i])):'—'])));});}
  if(action==='seller')sellerForm();if(action==='limits')limitsForm();if(action==='expense')editExpenseForm(id);
  if(action==='removeexpense')modal('Usunąć koszt z ewidencji?', '<p>Koszt przestanie być uwzględniany w raportach. Historia zmiany pozostanie.</p>'+noteField('reason','Powód'),async v=>{await api('removeexpense',{...v,id});await refresh();message('Koszt usunięty z ewidencji.');});
  if(action==='reports'||action==='clientreport')reportForm(id);
  if(action==='exportcurrent')exportCommerceCSV('raport.csv',window.pzReportRows||[]);
  if(action==='printreport'){const report=$('commerceReport');const frame=document.createElement('iframe');frame.style.cssText='position:fixed;left:-10000px;width:1000px;height:1000px';document.body.appendChild(frame);const d=frame.contentDocument;d.open();d.write('<!doctype html><html lang="pl"><meta charset="utf-8"><title>Raport Puchaty Zakątek</title><style>'+pzReportStyle+'body{font:12px Arial}table{border-collapse:collapse;width:100%}td,th{border:1px solid #ccc;padding:6px}button{display:none}@page{size:A4}</style><body>'+report.innerHTML+'</body></html>');d.close();frame.contentWindow.focus();frame.contentWindow.print();setTimeout(()=>frame.remove(),60000);}
  if(action==='ndg')await renderNDG(new Date().getFullYear());
  if(action==='ndgyear')modal('Rok ewidencji',field('year','Rok',ndgSummary.year,'number','min="2020" max="2100" required'),v=>renderNDG(v.year));
  if(action==='ndgexport')exportCommerceCSV('ewidencja-ndg-'+ndgSummary.year+'.csv',[['Data','Rodzaj','Dokument','Opis','Kwota PLN'],...ndgSummary.entries.map(x=>[x.date,x.kind,x.reference,x.description,(x.amount/100).toFixed(2)])]);
  if(action==='ndgentry'){const key=crypto.randomUUID();modal('Wpis / korekta ewidencji',selectField('kind','Rodzaj',[['due','Przychód należny'],['cash','Przychód otrzymany'],['cost','Koszt podatkowy']])+selectField('direction','Znak',[['plus','Zwiększenie'],['minus','Zmniejszenie']])+field('date','Data',today(),'date','required')+field('amount','Kwota PLN','','number','min="0.01" step="0.01" required')+field('reference','Dokument / podstawa','','text','required')+noteField('description','Uzasadnienie'),async v=>{await api('ndgentry',{...v,requestKey:key});await renderNDG(ndgSummary.year);});}
  if(action==='qualify')modal('Kwalifikacja kosztu',selectField('status','Ujęcie',[['eligible','Koszt uzyskania przychodu'],['excluded','Poza kosztami podatkowymi']])+field('paidDate','Data zapłaty',today(),'date')+noteField('reason','Uzasadnienie'),async v=>{await api('ndgcost',{...v,id});await renderNDG(ndgSummary.year);});
  if(action==='help')modal('Pomoc — Puchaty Zakątek 0.5.3', '<p>Rozliczenie wizyty automatycznie wystawia powiązaną fakturę zwolnioną z VAT. Potwierdzenie na taśmie 80 mm zawiera jego numer; znajdziesz je także w Dokumentach. Sprzedaż pozostałych towarów i usług może powstać jako osobny dokument.</p><p>Szkic można edytować, usuwać pozycje i zmieniać nabywcę. Wystawienie nadaje numer i zapisuje ruch magazynowy. Potwierdzenie niefiskalne nie jest paragonem z kasy fiskalnej.</p><p>Klientów i psy możesz archiwizować i przywracać. Raport klienta otworzysz w jego wierszu. Przed aktualizacją wykonaj kopię. Integracja GUS została pominięta zgodnie z ustaleniem.</p>',null);
  if(action==='backup')backupForm();
  if(action==='downloadbackup'||action==='downloadrestore'){const file=await api('backupscript',undefined,{restore:action==='downloadrestore'?1:0});const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([file.script],{type:'text/plain;charset=utf-8'}));a.download=file.name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
 }catch(err){if($('pzModal').open)$('modalError').textContent=err.message;else message(err.message,true);}
});
if(data)refreshCommerce().catch(e=>message(e.message,true));
async function renderNDG(year){ndgSummary=await api('ndg',undefined,{year});const n=ndgSummary;showView('business');$('commerceReport').innerHTML='<h3>Ewidencja NDG — '+n.year+'</h3>'+(n.firstBreach?'<p class="notice error">Odnotowano przekroczenie ustawowego limitu: '+esc(n.firstBreach)+'. <a href="https://www.podatki.gov.pl/poradniki-i-informatory/dzialalnosc-nierejestrowana" target="_blank" rel="noopener">Sprawdź obowiązki po przekroczeniu limitu</a>.</p>':'')+actionBtn('Wybierz rok','ndgyear')+actionBtn('Dodaj wpis / korektę','ndgentry')+actionBtn('Eksport ewidencji','ndgexport')+'<p>Przychód otrzymany: '+money(n.cash)+' • Koszty zakwalifikowane: '+money(n.cost)+' • Dochód: '+money(n.cash-n.cost)+'</p>'+pzLimitDashboard(n.quarters.map(q=>'Kwartał '+q.quarter),n.quarters.map(q=>q.due),n.quarters.map(q=>q.limit),'Ustawowy limit NDG')+table(['Kwartał','Przychód należny','Limit','Pozostało'],n.quarters.map(q=>row([q.quarter,money(q.due),q.limit===null?'Niezweryfikowany rok':money(q.limit),q.remaining===null?'—':money(q.remaining)])))+'<h4>Ewidencja dzienna</h4>'+table(['Data','Sprzedaż','Narastająco w kwartale'],n.daily.map(e=>row([esc(e.date),money(e.amount),money(e.quarterTotal)])))+'<details><summary>Uwagi do danych ('+n.issues.length+')</summary><ul>'+n.issues.map(i=>'<li>'+esc(i)+'</li>').join('')+'</ul></details><h4>Kwalifikacja kosztów</h4>'+table(['Dokument','Kwota','Kwalifikacja'],n.costs.map(e=>row([esc(e.document_no),money(Math.round(Number(e.amount_gross)*100)),actionBtn(e.qualification?.status||'Do sprawdzenia','qualify',e.rowid)])));}

