'use strict';
// Local SVG charts. Values remain integer grosze; no network or analytics.
const pzReportStyle=`.pz-dashboard{--rose:#bb637f;--mint:#519b8c;color:#492d38}.pz-kpis,.pz-charts{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:18px;margin:20px 0}.pz-kpis{grid-template-columns:repeat(3,minmax(0,1fr))}.pz-kpi,.pz-chart{background:#fff;border:1px solid #eedde2;border-radius:20px;padding:22px;min-width:0;break-inside:avoid}.pz-kpi{background:linear-gradient(135deg,#fff7f9,#f5faf8)}.pz-kpi span,.pz-subtitle{display:block;color:#76616a;font-size:13px;line-height:1.6}.pz-kpi strong{display:block;font-size:27px;margin-top:9px;overflow-wrap:anywhere}.pz-chart h4{font-size:17px;margin:0 0 7px}.pz-chart svg{display:block;width:100%;height:auto;margin:12px 0}.pz-chart text{font-family:Arial,sans-serif;fill:#68545d;font-size:11px}.pz-chart svg [tabindex]:focus{outline:2px solid #492d38}.pz-legend{display:flex;gap:12px;flex-wrap:wrap;font-size:12px}.pz-dot{display:inline-block;width:10px;height:10px;border-radius:50%;margin-right:6px}.pz-empty{padding:45px 12px;text-align:center;color:#806c74;background:#faf7f8;border-radius:12px}.pz-rank{margin:15px 0}.pz-rank>div{display:flex;justify-content:space-between;gap:12px;font-size:13px;margin-bottom:7px;overflow-wrap:anywhere}.pz-track{height:9px;background:#f4edf0;border-radius:12px;overflow:hidden}.pz-track i{display:block;height:100%;border-radius:12px;background:#bb637f}.pz-chart details{font-size:12px;margin-top:12px}.pz-chart summary{cursor:pointer}.pz-chart table{width:100%;font-size:12px}.pz-dashboard .pz-over{color:#ac294b}.pz-dashboard h3{font-size:24px}@media(max-width:760px){.pz-kpis,.pz-charts{grid-template-columns:1fr}.pz-chart,.pz-kpi{padding:16px}}@media print{.pz-kpis{grid-template-columns:repeat(3,minmax(0,1fr))}.pz-charts{grid-template-columns:1fr}.pz-chart{break-inside:avoid}.pz-chart details{display:none}.pz-kpi strong{font-size:19px}}`;
const pzColors=['#bb637f','#519b8c','#a28bc2','#c99b54','#688fae','#ad8172'];
function pzChartCard(title,subtitle,body){return '<section class="pz-chart"><h4>'+esc(title)+'</h4><span class="pz-subtitle">'+esc(subtitle)+'</span>'+body+'</section>';}
function pzChartTable(labels,series,unit="money"){return '<details><summary>Pokaż wartości wykresu</summary>'+table(['Okres',...series.map(s=>s.name)],labels.map((l,i)=>row([esc(l),...series.map(s=>unit==='money'?money(s.values[i]):s.values[i])])))+'</details>';}
function pzTimeline(labels,series,bars=false,unit="money"){
 const format=v=>unit==='money'?money(v):v+' wizyt';
 if(!labels.length)return '<p class="pz-empty">Brak danych w tym okresie</p>';
 const values=series.flatMap(s=>s.values),min=Math.min(0,...values),max=unit==='money'?Math.max(1,...values):Math.max(4,Math.ceil(Math.max(1,...values)/4)*4),range=max-min;
 const y=v=>220-(v-min)/range*175,x=i=>60+(i+.5)*480/labels.length;
 let svg='<svg viewBox="0 0 560 265" role="img" aria-label="'+esc(series.map(s=>s.name).join(' i '))+'">';
 for(let i=0;i<5;i++){const v=min+range*i/4;svg+='<line x1="60" x2="545" y1="'+y(v)+'" y2="'+y(v)+'" stroke="#eee4e8"/><text x="53" y="'+(y(v)+4)+'" text-anchor="end">'+esc((unit==='money'?v/100:v).toLocaleString('pl-PL',{maximumFractionDigits:0}))+'</text>';}
 svg+='<text x="10" y="20">'+(unit==='money'?'zł':'wizyty')+'</text>';
 series.forEach((s,k)=>{const c=pzColors[k];if(!bars)svg+='<polyline fill="none" stroke="'+c+'" stroke-width="3" points="'+s.values.map((v,i)=>x(i)+','+y(v)).join(' ')+'"/>';
 s.values.forEach((v,i)=>{const tip=esc(labels[i]+' — '+s.name+': '+format(v));if(bars){const w=Math.min(22,480/labels.length/(series.length+1));svg+='<rect tabindex="0" role="img" aria-label="'+tip+'" x="'+(x(i)+(k-series.length/2)*w)+'" y="'+Math.min(y(0),y(v))+'" width="'+Math.max(1,w-2)+'" height="'+Math.max(1,Math.abs(y(0)-y(v)))+'" fill="'+c+'" rx="2"><title>'+tip+'</title></rect>';}else svg+='<circle tabindex="0" role="img" aria-label="'+tip+'" cx="'+x(i)+'" cy="'+y(v)+'" r="4" fill="'+c+'"><title>'+tip+'</title></circle>';});});
 labels.forEach((l,i)=>{if(i%Math.max(1,Math.ceil(labels.length/8))===0)svg+='<text x="'+x(i)+'" y="245" text-anchor="middle">'+esc(l)+'</text>';});
 return svg+'</svg><div class="pz-legend">'+series.map((s,i)=>'<span><i class="pz-dot" style="background:'+pzColors[i]+'"></i>'+esc(s.name)+'</span>').join('')+'</div>'+pzChartTable(labels,series,unit);
}
function pzRank(items){if(!items.length)return '<p class="pz-empty">Brak danych w tym okresie</p>';const max=Math.max(1,...items.map(x=>Math.abs(x[1])));return items.map(([name,v])=>'<div class="pz-rank"><div><span>'+esc(name)+'</span><strong>'+money(v)+'</strong></div><div class="pz-track"><i style="width:'+Math.abs(v)/max*100+'%;background:'+(v<0?'#ac294b':'#bb637f')+'"></i></div></div>').join('');}
function pzDonut(items,label="Koszty ogółem"){items=items.filter(x=>x[1]>0);const total=items.reduce((n,x)=>n+x[1],0);if(!total)return '<p class="pz-empty">Brak dodatnich wartości w tym okresie</p>';let offset=0;const slices=items.map(([name,v],i)=>{const pct=v/total*100;const s='<circle cx="100" cy="100" r="68" fill="none" stroke="'+pzColors[i%pzColors.length]+'" stroke-width="24" pathLength="100" stroke-dasharray="'+pct+' '+(100-pct)+'" stroke-dashoffset="'+(-offset)+'" transform="rotate(-90 100 100)"><title>'+esc(name+': '+money(v))+'</title></circle>';offset+=pct;return s;}).join('');return '<svg viewBox="0 0 200 200" style="max-width:240px;margin:18px auto" role="img" aria-label="Udział kategorii">'+slices+'<text x="100" y="97" text-anchor="middle">'+esc(label)+'</text><text x="100" y="116" text-anchor="middle" style="font-weight:bold">'+esc(money(total))+'</text></svg>'+items.map(([n,v],i)=>'<div class="pz-rank"><div><span><i class="pz-dot" style="background:'+pzColors[i%pzColors.length]+'"></i>'+esc(n)+'</span><strong>'+money(v)+' · '+(v/total*100).toFixed(1)+'%</strong></div></div>').join('');}
function pzGroup(items,key,amount){const m=new Map();items.forEach(x=>m.set(key(x),(m.get(key(x))||0)+amount(x)));return [...m].sort((a,b)=>b[1]-a[1]);}
function pzSalesDashboard(from,to,sales,costs,clientId){
 const months=[];for(let y=Number(from.slice(0,4)),m=Number(from.slice(5,7));y*100+m<=Number(to.slice(0,4))*100+Number(to.slice(5,7));){months.push(y+'-'+String(m).padStart(2,'0'));if(++m>12){m=1;y++;}if(months.length>1200)break;}
 const aggregate=months.length>24,keys=aggregate?[...new Set(months.map(m=>m.slice(0,4)))]:months;
 const bucket=d=>d.slice(0,aggregate?4:7),sums=(rows,date,amount)=>{const map=new Map();rows.forEach(r=>map.set(bucket(date(r)),(map.get(bucket(date(r)))||0)+amount(r)));return keys.map(k=>map.get(k)||0);};
 const rev=sums(sales,s=>s.date,s=>s.total),exp=sums(costs,e=>e.expense_date,e=>Math.round(Number(e.amount_gross)*100)),total=rev.reduce((a,b)=>a+b,0),expense=exp.reduce((a,b)=>a+b,0),labels=keys.map(k=>aggregate?k:k.slice(5)+'.'+k.slice(2,4));
 const kpi=(label,value,sub)=>'<div class="pz-kpi"><span>'+esc(label)+'</span><strong>'+money(value)+'</strong><span>'+esc(sub)+'</span></div>';
 let body='<style>'+pzReportStyle+'</style><div class="pz-dashboard"><div class="pz-kpis">'+kpi('Sprzedaż po anulowaniach',total,'Według daty sprzedaży / anulowania')+(clientId?'':kpi('Zarejestrowane koszty',expense,'Według daty kosztu')+kpi('Sprzedaż minus koszty',total-expense,'Wynik zestawienia — nie dochód podatkowy'))+'</div><div class="pz-charts">';
 body+=pzChartCard('Jak zmienia się sprzedaż?',aggregate?'Przebieg roczny · kwoty w zł':'Przebieg miesięczny · kwoty w zł',pzTimeline(labels,[{name:'Sprzedaż',values:rev}]));
 if(!clientId){body+=pzChartCard('Sprzedaż i koszty','Porównanie w tym samym okresie',pzTimeline(labels,[{name:'Sprzedaż',values:rev},{name:'Koszty',values:exp}],true));const categories=pzGroup(costs,e=>e.category||'Bez kategorii',e=>Math.round(Number(e.amount_gross)*100));const shown=categories.slice(0,5);if(categories.length>5)shown.push(['Pozostałe',categories.slice(5).reduce((n,x)=>n+x[1],0)]);body+=pzChartCard('Na co wydajesz?','Udział dodatnich kosztów według kategorii',pzDonut(shown));body+=pzChartCard('Klienci — największa sprzedaż','Do 6 klientów · po uwzględnieniu anulowań',pzRank(pzGroup(sales,s=>s.client,s=>s.total).slice(0,6)));}
 body+=pzChartCard('Formy płatności','Wartość sprzedaży według wybranej metody; nie jest to raport otrzymanych wpłat. Dodatnie salda po anulowaniach.',pzDonut(pzGroup(sales,s=>s.payment||'Nie określono',s=>s.total),'Sprzedaż'));
 const docs=commerce.documents.filter(d=>d.state==='issued'&&d.saleDate>=from&&d.saleDate<=to&&(!clientId||Number(d.clientId)===Number(clientId)));
 body+=pzChartCard('Najpopularniejsze pozycje według wartości','Do 6 pozycji z aktualnie wystawionych dokumentów w tym okresie. Nie obejmuje wizyt bez dokumentu ani dokumentów anulowanych.',pzRank(pzGroup(docs.flatMap(d=>d.lines||[]),l=>l.name,l=>l.total).slice(0,6)));
 return body+'</div></div>';
}
function pzLimitDashboard(labels,due,limits,title){return '<style>'+pzReportStyle+'</style><div class="pz-dashboard">'+pzChartCard(title,'Przychód należny i limit w zł. Brak limitu nie oznacza limitu zerowego.',labels.map((l,i)=>{const limit=limits[i],value=due[i],pct=limit>0?value/limit*100:null;return '<div class="pz-rank"><div><span>'+esc(l)+'</span><strong class="'+(pct>100?'pz-over':'')+'">'+money(value)+(pct===null?' · brak limitu':' / '+money(limit)+' · '+pct.toFixed(1)+'%')+'</strong></div><div class="pz-track"><i style="width:'+(pct===null?0:Math.min(100,Math.max(0,pct)))+'%;background:'+(pct>100?'#ac294b':'#519b8c')+'"></i></div>'+(pct>100?'<span class="pz-subtitle pz-over">Przekroczono o '+money(value-limit)+'</span>':'')+'</div>';}).join(''))+'</div>';}
