<?php
function pz_mail_escape($value){return htmlspecialchars((string)$value,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8');}
function pz_mail_template($event,$details,$config,$logoSrc=null){
    $themes=array(
        'booking_confirmation'=>array('Rezerwacja potwierdzona','Do zobaczenia w salonie!','Zapisaliśmy termin pielęgnacji Twojego pupila. Szczegóły wizyty znajdziesz poniżej.','#e4f2eb','#315f50'),
        'appointment_changed'=>array('Nowy termin wizyty','Termin został zmieniony','Poniżej znajdziesz aktualny termin. Ta wiadomość zastępuje wcześniejsze potwierdzenie.','#eee8f6','#615073'),
        'appointment_cancelled'=>array('Wizyta odwołana','Rezerwacja została odwołana','Poniższy termin nie jest już zarezerwowany. Jeśli chcesz umówić nową wizytę, skontaktuj się z nami.','#eeebef','#645c69'),
        'appointment_reminder'=>array('Przypomnienie o wizycie','Czekamy na Was!','Zbliża się wizyta Twojego pupila w Puchatym Zakątku. Oto szczegóły rezerwacji.','#f8dce7','#873e55'),
        'invoice_after_payment'=>array('Płatność potwierdzona','Dziękujemy za wizytę!','W załączniku znajdziesz fakturę PDF za opłaconą usługę. Dziękujemy za zaufanie.','#e4f2eb','#315f50'),
        'test'=>array('Wiadomość testowa','Poczta jest gotowa','Ta wiadomość pozwala sprawdzić wygląd i dostarczenie poczty Puchatego Zakątka.','#f8dce7','#873e55')
    );
    $t=$themes[$event]??$themes['test'];$e='pz_mail_escape';
    if($logoSrc===null){$path=dirname(__DIR__).'/img/logo-transparent.png';if(is_file($path))$logoSrc='data:image/png;base64,'.base64_encode(file_get_contents($path));}
    $rows='';foreach($details as $label=>$value){if((string)$value==='')continue;$rows.='<tr><td style="padding:9px 0;border-bottom:1px solid #eadfda;color:#786a70;font-size:13px;width:35%;vertical-align:top">'.$e($label).'</td><td style="padding:9px 0 9px 12px;border-bottom:1px solid #eadfda;color:#3f3037;font-size:16px;font-weight:bold;overflow-wrap:anywhere">'.nl2br($e($value)).'</td></tr>';}
    $phone=trim((string)($config['salon']['phone']??''));$address=trim((string)($config['salon']['address']??''));$reply=$config['sender']['reply_to']??'';if(!$reply)$reply=$config['sender']['address']??'';
    $contact=$address!==''?'<p style="margin:0 0 10px">'.nl2br($e($address)).'</p>':'';
    if($phone!=='')$contact.='<p style="margin:0 0 10px">Telefon: <a style="color:#873e55" href="tel:'.$e(preg_replace('/[^+0-9]/','',$phone)).'">'.$e($phone).'</a></p>';
    if(filter_var($reply,FILTER_VALIDATE_EMAIL))$contact.='<p style="margin:0"><a href="mailto:'.$e($reply).'" style="color:#873e55;text-decoration:underline">'.$e($reply).'</a></p>';
    return '<!doctype html><html lang="pl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'.$e($t[0]).'</title></head><body style="margin:0;padding:0;background:#fff7f3;font-family:Arial,Helvetica,sans-serif;color:#3f3037"><div style="display:none;max-height:0;overflow:hidden;mso-hide:all">'.$e($t[0]).' — Puchaty Zakątek</div><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="background:#fff7f3"><tr><td align="center" style="padding:24px 12px"><table role="presentation" width="600" cellspacing="0" cellpadding="0" style="width:100%;max-width:600px;border:1px solid #ecd8df;border-radius:24px;background:#fffdfb"><tr><td align="center" style="padding:28px 24px 22px;background:#edf7f1;border-radius:24px 24px 0 0">'.($logoSrc?'<img src="'.$e($logoSrc).'" alt="Puchaty Zakątek" width="120" height="120" style="display:block;width:120px;height:120px;border:0;margin:0 auto 12px">':'').'<p style="margin:0;color:#873e55;font-size:24px;font-weight:bold">Puchaty Zakątek</p><p style="margin:8px 0 0;font-size:11px;letter-spacing:1px;color:#596e63">SPA DLA PSÓW · STRZYŻENIE &amp; MYCIE</p></td></tr><tr><td style="padding:28px 24px"><span style="display:inline-block;padding:7px 12px;background:'.$t[3].';color:'.$t[4].';border-radius:20px;font-size:12px;font-weight:bold">'.$e($t[0]).'</span><h1 style="margin:20px 0 14px;font-size:27px;line-height:1.25;color:#873e55">'.$e($t[1]).'</h1><p style="font-size:16px;line-height:1.6;margin:0 0 20px">Dzień dobry!<br>'.$e($t[2]).'</p>'.($rows?'<table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="background:#fff6f8;border:1px solid #efdae2;border-radius:16px"><tr><td style="padding:12px 16px"><table width="100%" cellspacing="0" cellpadding="0">'.$rows.'</table></td></tr></table>':'').'<p style="margin:20px 0;font-size:14px;line-height:1.6;color:#786a70">Masz pytanie? Odpowiedz na tę wiadomość'.($phone!==''?' lub zadzwoń do nas':'').'.</p><p style="margin:0;font-size:15px;line-height:1.6">'.$e($config['salon']['footer']??'Do zobaczenia w Puchatym Zakątku!').'<br><strong>Zespół Puchatego Zakątka</strong></p></td></tr><tr><td style="padding:22px 24px;background:#f5edf2;border-radius:0 0 24px 24px;font-size:13px;line-height:1.6;color:#6d5964">'.$contact.'<p style="margin:14px 0 0;font-size:11px">Wiadomość dotycząca obsługi wizyty · Puchaty Zakątek</p></td></tr></table></td></tr></table></body></html>';
}
